# Use an official Python runtime as a parent image
FROM apache/airflow:2.9.0-python3.9

# Copy the requirements.txt file into the container at /home/ubuntu/airflow
# COPY requirements.txt .

# Install any needed packages specified in requirements.txt
# RUN pip install --no-cache-dir -r requirements.txt
